"""Game weapon and ammo IDs from src/include/constants.h (weaponnum enum)."""

WEAPON_FALCON2 = 0x02
WEAPON_MAGSEC4 = 0x05
WEAPON_MAULER = 0x06
WEAPON_CMP150 = 0x0A
WEAPON_AR34 = 0x11
WEAPON_SHOTGUN = 0x13
WEAPON_LAPTOPGUN = 0x0E
WEAPON_SNIPERRIFLE = 0x15
WEAPON_SUPERDRAGON = 0x12
WEAPON_ROCKETLAUNCHER = 0x18
WEAPON_CROSSBOW = 0x1B
WEAPON_TRANQUILIZER = 0x1C

# CHR pickup models (constants.h MODEL_CHR*)
MODEL_CHRAR34 = 0x00FE
MODEL_CHRSHOTGUN = 0x0106
MODEL_CHRFALCON2 = 0x00F5
MODEL_CHRLEEGUN1 = 0x00F6
MODEL_CHRMAULER = 0x00F7
MODEL_CHRCMP150 = 0x00FD
MODEL_CHRPCGUN = 0x0105
MODEL_CHRSNIPERRIFLE = 0x010C
MODEL_CHRSUPERDRAGON = 0x0100
MODEL_CHRDYROCKET = 0x0108
MODEL_CHRCROSSBOW = 0x010D
MODEL_CHRDRUGGUN = 0x0110

# Explicit models for floor weapon props (model 0 works when MP resolves at runtime,
# but embedding IDs keeps setup binaries self-describing for debug/tools).
WEAPON_FLOOR_MODEL = {
    WEAPON_FALCON2: MODEL_CHRFALCON2,
    WEAPON_MAGSEC4: MODEL_CHRLEEGUN1,
    WEAPON_MAULER: MODEL_CHRMAULER,
    WEAPON_CMP150: MODEL_CHRCMP150,
    WEAPON_AR34: MODEL_CHRAR34,
    WEAPON_SHOTGUN: MODEL_CHRSHOTGUN,
    WEAPON_LAPTOPGUN: MODEL_CHRPCGUN,
    WEAPON_SNIPERRIFLE: MODEL_CHRSNIPERRIFLE,
    WEAPON_SUPERDRAGON: MODEL_CHRSUPERDRAGON,
    WEAPON_ROCKETLAUNCHER: MODEL_CHRDYROCKET,
    WEAPON_CROSSBOW: MODEL_CHRCROSSBOW,
    WEAPON_TRANQUILIZER: MODEL_CHRDRUGGUN,
}

AMMOTYPE_PISTOL = 0x01
AMMOTYPE_RIFLE = 0x03
AMMOTYPE_SHOTGUN = 0x04
AMMOTYPE_ROCKET = 0x05

OBJFLAG_FALL = 0x00000001
OBJFLAG2_IMMUNETOANTI = 0x00000001
MODEL_MULTI_AMMO_CRATE = 0x00C1

# Default loadout intro weapons (Falcon2, CMP150, AR34, MagSec4)
INTRO_WEAPONS = (WEAPON_FALCON2, WEAPON_CMP150, 0x11, WEAPON_MAGSEC4)
INTRO_AMMO = (AMMOTYPE_PISTOL, AMMOTYPE_RIFLE, AMMOTYPE_RIFLE, AMMOTYPE_PISTOL)
