#!/usr/bin/env python3
"""Convert pass-2 editor JSON into a pdmap level module (src/levels/<name>.py).

CLI:
  python3 json_to_level.py map.json > src/levels/foo.py
  python3 json_to_level.py map.json -o src/levels/foo.py

JSON schema (editor export):
  {
    "name": "csim",
    "box_half": 5000,
    "box_height": 3000,
    "pads": [
      {"index": 0, "type": "spawn", "x": 0, "y": 10, "z": 0, "room": 1},
      {"index": 1, "type": "weapon", "x": 0, "y": 10, "z": 0, "room": 1, "weapon": 17},
      {"index": 2, "type": "ammo", "x": 0, "y": 10, "z": 0, "room": 1,
       "ammoType": 4, "quantity": 200},
      {"index": 3, "type": "scenario", "x": 0, "y": 10, "z": 0, "room": 1,
       "scenario": "hill", "team": 0}
    ]
  }

Pad indices must be contiguous 0..N-1 (array order = pad index).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any

# Known weapon / ammo IDs from tools/pdmap/weapons.py (fallback to hex literals).
WEAPON_CONST: dict[int, str] = {
    0x02: "W.WEAPON_FALCON2",
    0x05: "W.WEAPON_MAGSEC4",
    0x06: "W.WEAPON_MAULER",
    0x0A: "W.WEAPON_CMP150",
    0x0E: "W.WEAPON_LAPTOPGUN",
    0x12: "W.WEAPON_SUPERDRAGON",
    0x15: "W.WEAPON_SNIPERRIFLE",
    0x18: "W.WEAPON_ROCKETLAUNCHER",
    0x1B: "W.WEAPON_CROSSBOW",
    0x1C: "W.WEAPON_TRANQUILIZER",
}

AMMO_CONST: dict[int, str] = {
    0x01: "W.AMMOTYPE_PISTOL",
    0x03: "W.AMMOTYPE_RIFLE",
    0x04: "W.AMMOTYPE_SHOTGUN",
    0x05: "W.AMMOTYPE_ROCKET",
}

_VALID_NAME = re.compile(r"^[a-z][a-z0-9_]{0,31}$")


def _fmt_num(v: float | int) -> str:
    """Render coordinates as clean floats (no trailing .0 noise when integral)."""
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    if isinstance(v, int):
        return f"{v}.0" if abs(v) >= 1000 or v == 0 else str(v)
    return f"{v:.1f}".rstrip("0").rstrip(".")


def _weapon_expr(wid: int) -> str:
    return WEAPON_CONST.get(wid, f"0x{wid:02x}")


def _ammo_expr(aid: int) -> str:
    return AMMO_CONST.get(aid, f"0x{aid:02x}")


def _validate_name(name: str) -> str:
    name = (name or "map").strip().lower()
    if not _VALID_NAME.match(name):
        raise ValueError(
            f"Invalid level name {name!r}; use lowercase letters, digits, underscore "
            "(must start with a letter)."
        )
    return name


def json_to_level_py(data: dict[str, Any]) -> str:
    """Render editor JSON as a complete src/levels/<name>.py module string."""
    name = _validate_name(str(data.get("name", "map")))
    half = float(data.get("box_half", 5000))
    height = float(data.get("box_height", 3000))
    pads: list[dict[str, Any]] = list(data.get("pads") or [])

    spawn_pads: list[tuple[int, dict]] = []
    weapon_pads: list[tuple[int, dict]] = []
    ammo_pads: list[tuple[int, dict]] = []
    scenario_pads: list[tuple[int, dict]] = []
    other_pads: list[tuple[int, dict]] = []

    for i, p in enumerate(pads):
        idx = int(p.get("index", i))
        if idx != i:
            raise ValueError(f"Pad at array position {i} has index={idx}; indices must be contiguous 0..N-1.")
        kind = p.get("type", "other")
        bucket = {
            "spawn": spawn_pads,
            "weapon": weapon_pads,
            "ammo": ammo_pads,
            "scenario": scenario_pads,
        }.get(kind, other_pads)
        bucket.append((i, p))

    lines: list[str] = []
    append = lines.append

    append("# Generated by journal/uff_viewer (pass-3 export).")
    append("")
    append("from tools.pdmap.builders import (")
    append("    add_loadout_intro,")
    if weapon_pads:
        append("    add_floor_weapons,")
    if ammo_pads:
        append("    add_ammo_row,")
    append("    floor_box_tiles,")
    append(")")
    append("from tools.pdmap.core import MapDef")
    intro_imports: set[str] = set()
    if spawn_pads:
        intro_imports.add("Spawn")
    for _, p in scenario_pads:
        if p.get("scenario") == "case":
            intro_imports.add("Case")
        else:
            intro_imports.add("Hill")
    if intro_imports:
        append(f"from tools.pdmap.intro import {', '.join(sorted(intro_imports))}")
    prop_imports: set[str] = set()
    if weapon_pads:
        prop_imports.add("Weapon as WeaponProp")
    if ammo_pads:
        # Use AmmoCrate directly when we need per-crate ammotype; add_ammo_row is uniform.
        pass
    if prop_imports:
        append(f"from tools.pdmap.props import {', '.join(sorted(prop_imports))}")
    append("from tools.pdmap import weapons as W")
    append("")
    append("# Arena dimensions — shared by floor tiles and generic box seg (--seg).")
    append(f"BOX_HALF = {_fmt_num(half)}")
    append(f"BOX_HEIGHT = {_fmt_num(height)}")
    append("")
    append("# Pads slightly above Y=0 so ground search accepts the floor (see MAP_CREATION.md).")
    append("SPAWN_Y = 10.0")
    append("")
    append("")
    append("def build() -> MapDef:")
    append(f'    g = MapDef("{name}")')
    append("")
    append("    # --- Pads (indices MUST match array order 0..N-1) ---")

    for i, p in enumerate(pads):
        x, y, z = float(p.get("x", 0)), float(p.get("y", 0)), float(p.get("z", 0))
        room = int(p.get("room", 1))
        kind = p.get("type", "other")
        append(
            f"    g.add_pad(index={i}, x={_fmt_num(x)}, y={_fmt_num(y)}, "
            f"z={_fmt_num(z)}, room={room})  # {kind}"
        )

    if spawn_pads:
        append("")
        append("    # --- Spawn intro commands ---")
        for i, _p in spawn_pads:
            append(f"    g.add_intro(Spawn(pad={i}))")

    if weapon_pads:
        append("")
        append("    # --- Weapon pickups (floor props) ---")
        pairs = ", ".join(f"({i}, {_weapon_expr(int(p['weapon']))})" for i, p in weapon_pads if "weapon" in p)
        if pairs:
            append(f"    add_floor_weapons(g, [{pairs}])")
        missing = [i for i, p in weapon_pads if "weapon" not in p]
        if missing:
            append(f"    # WARNING: weapon pad(s) {missing} missing weapon id — add manually")

    if ammo_pads:
        append("")
        append("    # --- Ammo crates (floor props) ---")
        # Group by ammotype so we can use add_ammo_row when uniform.
        by_type: dict[int, list[int]] = {}
        for i, p in ammo_pads:
            aid = int(p.get("ammoType", 0x04))
            by_type.setdefault(aid, []).append(i)
        for aid, indices in sorted(by_type.items()):
            idx_str = ", ".join(str(i) for i in indices)
            append(f"    add_ammo_row(g, [{idx_str}], ammotype={_ammo_expr(aid)})")

    if scenario_pads:
        append("")
        append("    # --- Scenario anchors (Capture the Case / King of the Hill) ---")
        for i, p in scenario_pads:
            sc = p.get("scenario", "hill")
            team = int(p.get("team", 0))
            if sc == "case":
                append(f"    g.add_intro(Case(team={team}, pad={i}))")
                append(f"    # NOTE: CaseRespawn pad not in editor export — add a second scenario pad if needed")
            else:
                append(f"    g.add_intro(Hill(pad={i}))")

    append("")
    append("    add_loadout_intro(g)")
    append("    return g")
    append("")
    append("")
    append("def build_tiles_json():")
    append(f'    return floor_box_tiles("{name}", half=BOX_HALF, y=0.0, room_index=1)')
    append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Convert editor JSON to a pdmap level .py module.")
    parser.add_argument("json_file", nargs="?", help="Editor JSON file (default: stdin)")
    parser.add_argument("-o", "--output", help="Write to file instead of stdout")
    args = parser.parse_args(argv)

    if args.json_file:
        with open(args.json_file, encoding="utf-8") as fp:
            data = json.load(fp)
    else:
        data = json.load(sys.stdin)

    py_src = json_to_level_py(data)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fp:
            fp.write(py_src)
    else:
        sys.stdout.write(py_src)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
