#!/usr/bin/env python3
"""One-shot build + play pipeline for maps exported from the uff viewer editor.

Reads editor JSON (file or stdin), builds assets deterministically via
``tools.pdmap.from_json`` + ``tools.pdmap.pipeline`` (no level module required),
optionally writes ``src/levels/<name>.py``, deploys, and launches ``--test-map``.

Examples:
  python3 journal/uff_viewer/test_map.py map.json --play
  python3 journal/uff_viewer/test_map.py - --deploy-as uff --play <<'EOF'
  {"name":"uff","box_half":5000,"pads":[{"type":"spawn","x":0,"y":10,"z":0}]}
  EOF
  python3 tools/pdmap.py from-json map.json --deploy-as uff --play
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
_env_root = os.environ.get("PD_REPO_ROOT", "").strip()
ROOT = os.path.abspath(_env_root) if _env_root else os.path.dirname(os.path.dirname(HERE))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from tools.pdmap.core import ROOT as PDMAP_ROOT  # noqa: E402
from tools.pdmap.from_json import EditorMapSpec  # noqa: E402
from tools.pdmap.level_codegen import render_level_module  # noqa: E402
from tools.pdmap.pipeline import build_from_spec  # noqa: E402
from tools.pdmap.play import (  # noqa: E402
    MOD_CHOICES,
    SCENARIO_CHOICES,
    TEST_MAP_SLOT,
    detect_pd_binary,
    play_command,
)

assert ROOT == PDMAP_ROOT

# Default weapon loadout slots for --test-map (Falcon2, CMP150, AR34, MagSec4, None, Shield).
DEFAULT_LOADOUT = [0x01, 0x09, 0x10, 0x04, 0x00, 0x25]


def _mod_bgdata(mod_key: str) -> str:
    if mod_key not in MOD_CHOICES:
        raise ValueError(f"Unknown mod {mod_key!r}; choose from {', '.join(MOD_CHOICES)}")
    return os.path.join(ROOT, MOD_CHOICES[mod_key], "files", "bgdata")


def _load_json(path: str | None) -> dict[str, Any]:
    if path in (None, "-"):
        return json.load(sys.stdin)
    with open(path, encoding="utf-8") as fp:
        return json.load(fp)


def write_level_module(spec: EditorMapSpec, *, backup: bool) -> str:
    """Optionally persist ``src/levels/<name>.py`` for git / hand-editing."""
    level_path = os.path.join(ROOT, "src", "levels", f"{spec.name}.py")
    py_src = render_level_module(spec)

    if backup and os.path.exists(level_path):
        bak = level_path + ".bak"
        shutil.copy2(level_path, bak)
        print(f"  Backed up existing level -> {os.path.relpath(bak, ROOT)}")

    os.makedirs(os.path.dirname(level_path), exist_ok=True)
    with open(level_path, "w", encoding="utf-8") as fp:
        fp.write(py_src)
    print(f"  Wrote level module -> {os.path.relpath(level_path, ROOT)}")
    return level_path


def emit_last_artifacts(
    data: dict[str, Any],
    shell_script: str,
    *,
    json_path: str | None = None,
    sh_path: str | None = None,
) -> None:
    """Persist JSON + shell script beside the viewer for copy/paste workflows."""
    json_path = json_path or os.path.join(HERE, ".last_test.json")
    sh_path = sh_path or os.path.join(HERE, ".last_test.sh")
    with open(json_path, "w", encoding="utf-8") as fp:
        json.dump(data, fp, indent=2)
    with open(sh_path, "w", encoding="utf-8") as fp:
        fp.write(shell_script)
    os.chmod(sh_path, 0o755)
    print(f"  Wrote {os.path.relpath(json_path, ROOT)}")
    print(f"  Wrote {os.path.relpath(sh_path, ROOT)}")


def build_shell_script(args: argparse.Namespace, data: dict[str, Any]) -> str:
    """Self-contained script: JSON heredoc + test_map.py invocation."""
    json_blob = json.dumps(data, indent=2)
    flags = [
        f"--level {args.level}",
        f"--mod {args.mod}",
        f"--scenario {args.scenario}",
    ]
    if args.seg:
        flags.append("--seg")
    if args.deploy:
        flags.append("--deploy")
    if args.skip_validate:
        flags.append("--skip-validate")
    if args.rebuild_game:
        flags.append("--rebuild-game")
    if args.play:
        flags.append("--play")
    if args.verbose:
        flags.append("--verbose")
    if args.write_level:
        flags.append("--write-level")
    if args.backup:
        flags.append("--backup")
    if args.deploy_as and args.deploy_as != args.level:
        flags.append(f"--deploy-as {args.deploy_as}")

    flag_line = " \\\n  ".join(flags)
    return (
        "#!/bin/bash\n"
        "# Generated by journal/uff_viewer — run from repo root.\n"
        "set -euo pipefail\n"
        f'cd "{ROOT}"\n'
        "python3 journal/uff_viewer/test_map.py - \\\n"
        f"  {flag_line} <<'__PDMAP_EDITOR_JSON__'\n"
        f"{json_blob}\n"
        "__PDMAP_EDITOR_JSON__\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build and optionally play a map from uff viewer editor JSON.",
    )
    parser.add_argument("json_file", nargs="?", default="-", help="Editor JSON file (default: stdin)")
    parser.add_argument("--level", help="Editor map name (default: JSON name field)")
    parser.add_argument(
        "--deploy-as",
        help="Asset name for build/deploy (default: --level). Use 'uff' for --test-map.",
    )
    parser.add_argument(
        "--mod",
        choices=sorted(MOD_CHOICES),
        default="mod_allinone",
        help="Mod directory to deploy bgdata into (default: mod_allinone)",
    )
    parser.add_argument(
        "--scenario",
        type=int,
        choices=sorted(SCENARIO_CHOICES),
        default=0,
        help="MP scenario for --test-map (default: 0 Combat)",
    )
    parser.add_argument("--seg", action="store_true", default=True, help="Build box seg (default: on)")
    parser.add_argument("--no-seg", dest="seg", action="store_false", help="Skip seg build")
    parser.add_argument("--deploy", action="store_true", default=True, help="Deploy to mod (default: on)")
    parser.add_argument("--no-deploy", dest="deploy", action="store_false", help="Skip mod deploy")
    parser.add_argument("--skip-validate", action="store_true", help="Skip pdmap validate after build")
    parser.add_argument("--rebuild-game", action="store_true", help="Run cmake --build build --target pd")
    parser.add_argument("--play", action="store_true", help="Launch pd binary after build")
    parser.add_argument("--dry-run", action="store_true", help="Print planned commands only")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose build logging")
    parser.add_argument(
        "--write-level",
        action="store_true",
        help="Also write src/levels/<deploy-as>.py (optional; not required to play)",
    )
    parser.add_argument(
        "--backup",
        action="store_true",
        default=True,
        help="Backup existing level module when --write-level (default: on)",
    )
    parser.add_argument("--no-backup", dest="backup", action="store_false")
    parser.add_argument("--binary", help="Path to pd binary (default: auto-detect pd.arm64 / pd.x86_64)")
    parser.add_argument(
        "--write-artifacts",
        action="store_true",
        help="Also write journal/uff_viewer/.last_test.json and .last_test.sh",
    )
    args = parser.parse_args(argv)

    data = _load_json(args.json_file if args.json_file != "-" else None)
    level_name = (args.level or data.get("name") or "map").strip().lower()
    deploy_name = (args.deploy_as or level_name).strip().lower()
    data["name"] = level_name

    pd_binary = args.binary or detect_pd_binary()
    use_test_map = deploy_name == TEST_MAP_SLOT

    print(f"Editor name  : {level_name}")
    print(f"Deploy/build : {deploy_name}")
    print(f"Mod target   : {args.mod} ({MOD_CHOICES[args.mod]})")
    print(f"Scenario     : {args.scenario} ({SCENARIO_CHOICES[args.scenario]})")
    if args.play and not use_test_map:
        print(
            f"WARNING: --test-map loads the '{TEST_MAP_SLOT}' asset slot (STAGE_TEST_UFF). "
            f"Deploy name is '{deploy_name}' — game may not load your map unless stage is registered.",
            file=sys.stderr,
        )

    shell_script = build_shell_script(
        argparse.Namespace(**{**vars(args), "level": level_name, "deploy_as": deploy_name}),
        data,
    )

    if args.dry_run:
        print("\n--- dry run ---")
        print(shell_script)
        play = play_command(
            mod_key=args.mod,
            scenario=args.scenario,
            pd_binary=pd_binary,
            deploy_name=deploy_name if args.play else TEST_MAP_SLOT,
        )
        print("\n# play command:")
        print(" ".join(play))
        return 0

    if args.write_artifacts:
        emit_last_artifacts(data, shell_script)

    build_data = dict(data)
    build_data["name"] = deploy_name

    try:
        spec = EditorMapSpec.from_json(build_data, deploy_name=deploy_name)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.write_level:
        write_level_module(spec, backup=args.backup)

    print(f"\nBuilding {deploy_name} (direct from JSON)...")
    try:
        errors, warnings = build_from_spec(
            spec,
            deploy=args.deploy,
            want_seg=args.seg,
            seg_mode="empty" if args.seg else None,
            mod_dirs=[_mod_bgdata(args.mod)] if args.deploy else None,
            skip_validate=args.skip_validate,
            verbose=args.verbose or True,
        )
    except Exception as exc:
        print(f"ERROR: build failed: {exc}", file=sys.stderr)
        return 1

    for w in warnings:
        print(f"  [WARN] {w}")
    for e in errors:
        print(f"  [ERROR] {e}", file=sys.stderr)
    if errors:
        print(f"Build finished with {len(errors)} validation error(s)", file=sys.stderr)
        return 1

    if args.rebuild_game:
        print("\nRebuilding game binary...")
        subprocess.run(
            ["cmake", "--build", "build", "--target", "pd", "-j4"],
            cwd=ROOT,
            check=True,
        )

    if args.play:
        if not os.path.isfile(pd_binary):
            print(f"ERROR: pd binary not found at {pd_binary}", file=sys.stderr)
            print("Build the game first: cmake --build build --target pd", file=sys.stderr)
            return 1
        cmd = play_command(
            mod_key=args.mod,
            scenario=args.scenario,
            pd_binary=pd_binary,
            deploy_name=deploy_name,
        )
        print("\nLaunching:", " ".join(cmd))
        subprocess.run(cmd, cwd=ROOT, check=False)

    print("\nDone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
