# Generated by journal/uff_viewer (pass-3 export).

from tools.pdmap.builders import (
    add_loadout_intro,
    add_floor_weapons,
    add_ammo_row,
    floor_box_tiles,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Case, CaseRespawn, Hill, Spawn
from tools.pdmap import weapons as W

# Arena dimensions — shared by floor tiles and generic box seg (--seg).
BOX_HALF = 2500.0
BOX_HEIGHT = 2000.0

# Pads slightly above Y=0 so ground search accepts the floor (see MAP_CREATION.md).
SPAWN_Y = 10.0


def build() -> MapDef:
    g = MapDef("my_arena")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=-2000.0, y=10, z=-2000.0, room=1)  # spawn
    g.add_pad(index=1, x=2000.0, y=10, z=-2000.0, room=1)  # spawn
    g.add_pad(index=2, x=-2000.0, y=10, z=2000.0, room=1)  # spawn
    g.add_pad(index=3, x=2000.0, y=10, z=2000.0, room=1)  # spawn
    g.add_pad(index=4, x=0.0, y=10, z=-1500.0, room=1)  # weapon
    g.add_pad(index=5, x=0.0, y=10, z=1500.0, room=1)  # weapon
    g.add_pad(index=6, x=0.0, y=10, z=0.0, room=1)  # ammo
    g.add_pad(index=7, x=0.0, y=10, z=-500, room=1)  # scenario case
    g.add_pad(index=8, x=0.0, y=10, z=500, room=1)  # scenario case_respawn
    g.add_pad(index=9, x=500.0, y=10, z=0.0, room=1)  # scenario hill

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))
    g.add_intro(Spawn(pad=1))
    g.add_intro(Spawn(pad=2))
    g.add_intro(Spawn(pad=3))

    # --- Weapon pickups (floor props) ---
    add_floor_weapons(g, [(4, 0x11), (5, 0x13)])

    # --- Ammo crates (floor props) ---
    add_ammo_row(g, [6], ammotype=W.AMMOTYPE_SHOTGUN)

    # --- Scenario anchors (Capture the Case / King of the Hill) ---
    g.add_intro(Case(team=0, pad=7))
    g.add_intro(CaseRespawn(team=0, pad=8))
    g.add_intro(Hill(pad=9))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_tiles("my_arena", half=BOX_HALF, y=0.0, room_index=1)
