# Generated by journal/uff_viewer (pass-3 export).

from tools.pdmap.builders import (
    add_loadout_intro,
    add_floor_weapons,
    add_ammo_row,
    floor_box_tiles,
)
from tools.pdmap.core import MapDef
from tools.pdmap.intro import Hill, Spawn
from tools.pdmap import weapons as W

# Arena dimensions — shared by floor tiles and generic box seg (--seg).
BOX_HALF = 5000.0
BOX_HEIGHT = 3000.0

# Pads slightly above Y=0 so ground search accepts the floor (see MAP_CREATION.md).
SPAWN_Y = 10.0


def build() -> MapDef:
    g = MapDef("testarena")

    # --- Pads (indices MUST match array order 0..N-1) ---
    g.add_pad(index=0, x=-2000.0, y=10, z=-2000.0, room=1)  # spawn
    g.add_pad(index=1, x=2000.0, y=10, z=-2000.0, room=1)  # spawn
    g.add_pad(index=2, x=-2000.0, y=10, z=2000.0, room=1)  # spawn
    g.add_pad(index=3, x=2000.0, y=10, z=2000.0, room=1)  # spawn
    g.add_pad(index=4, x=0.0, y=10, z=0.0, room=1)  # weapon
    g.add_pad(index=5, x=1500.0, y=10, z=0.0, room=1)  # ammo
    g.add_pad(index=6, x=0.0, y=10, z=1500.0, room=1)  # scenario

    # --- Spawn intro commands ---
    g.add_intro(Spawn(pad=0))
    g.add_intro(Spawn(pad=1))
    g.add_intro(Spawn(pad=2))
    g.add_intro(Spawn(pad=3))

    # --- Weapon pickups (floor props) ---
    add_floor_weapons(g, [(4, W.WEAPON_CMP150)])

    # --- Ammo crates (floor props) ---
    add_ammo_row(g, [5], ammotype=W.AMMOTYPE_RIFLE)

    # --- Scenario anchors (Capture the Case / King of the Hill) ---
    g.add_intro(Hill(pad=6))

    add_loadout_intro(g)
    return g


def build_tiles_json():
    return floor_box_tiles("testarena", half=BOX_HALF, y=0.0, room_index=1)
